# Generated by Django 2.1.2 on 2018-10-27 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWorkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('platform_type', models.IntegerField(choices=[('1', 'Slack')])),
                ('platform_id', models.CharField(max_length=255)),
                ('connection_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MegatronChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform_channel_id', models.CharField(max_length=63)),
                ('last_message_sent', models.DateTimeField(auto_now_add=True)),
                ('platform_user_id', models.CharField(max_length=127)),
                ('is_paused', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MegatronIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_type', models.IntegerField(choices=[('1', 'Slack')])),
                ('platform_id', models.CharField(max_length=255)),
                ('connection_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MegatronMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_msg_id', models.CharField(max_length=255)),
                ('customer_msg_id', models.CharField(max_length=255)),
                ('megatron_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megatron.MegatronChannel')),
            ],
        ),
        migrations.CreateModel(
            name='MegatronUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('organization_name', models.CharField(max_length=255)),
                ('verification_token', models.CharField(max_length=255)),
                ('command_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megatron.MegatronUser')),
            ],
        ),
        migrations.AddField(
            model_name='megatronintegration',
            name='megatron_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megatron.MegatronUser'),
        ),
        migrations.AddField(
            model_name='megatronchannel',
            name='megatron_integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='megatron.MegatronIntegration'),
        ),
        migrations.AddField(
            model_name='megatronchannel',
            name='megatron_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megatron.MegatronUser'),
        ),
        migrations.AddField(
            model_name='megatronchannel',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='megatron.CustomerWorkspace'),
        ),
        migrations.AlterUniqueTogether(
            name='customerworkspace',
            unique_together={('platform_type', 'platform_id')},
        ),
        migrations.AlterUniqueTogether(
            name='megatronintegration',
            unique_together={('platform_type', 'platform_id')},
        ),
        migrations.AlterUniqueTogether(
            name='megatronchannel',
            unique_together={('workspace', 'platform_channel_id'), ('workspace', 'platform_user_id')},
        ),
    ]
