# Generated by Django 2.1.2 on 2018-12-01 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('megatron', '0003_auto_20181201_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='username',
            field=models.CharField(default='Unknown Name', max_length=250),
            preserve_default=False,
        ),
    ]
