# Generated by Django 2.1.2 on 2019-01-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megatron', '0004_auto_20181201_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerworkspace',
            name='domain',
            field=models.CharField(default='unknown_domain', max_length=255),
            preserve_default=False,
        ),
    ]
