# Generated by Django 2.1.2 on 2019-01-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megatron', '0005_customerworkspace_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megatronmessage',
            name='customer_msg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='megatronmessage',
            name='integration_msg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
