# Generated by Django 2.1.2 on 2019-01-19 14:22

from django.db import migrations


def delete_dupes(apps, schema_editor):
    MegatronMessage = apps.get_model('megatron', 'MegatronMessage')
    for row in MegatronMessage.objects.all():
        integration_dupes = MegatronMessage.objects.filter(
                megatron_channel=row.megatron_channel,
                integration_msg_id=row.integration_msg_id
        ).exclude(id=row.id)
        integration_dupes.delete()
        customer_dupes = MegatronMessage.objects.filter(
                megatron_channel=row.megatron_channel,
                customer_msg_id=row.customer_msg_id
        ).exclude(id=row.id)
        customer_dupes.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('megatron', '0006_auto_20190119_1359'),
    ]

    operations = [
        migrations.RunPython(delete_dupes),
        migrations.AlterUniqueTogether(
            name='megatronmessage',
            unique_together={('integration_msg_id', 'megatron_channel'), ('customer_msg_id', 'megatron_channel')},
        ),
    ]
