# Generated by Django 2.1.2 on 2019-02-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megatron', '0007_auto_20190119_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='real_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='username',
            field=models.CharField(default='', max_length=250),
        ),
    ]
