# Generated by Django 2.2.4 on 2019-11-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megatron', '0008_auto_20190204_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZendeskTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zendesk_id', models.IntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('megatron_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megatron.MegatronChannel')),
            ],
            options={
                'unique_together': {('zendesk_id', 'megatron_channel')},
            },
        ),
    ]
