# Generated by Django 2.2.9 on 2020-01-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megatron', '0008_auto_20190204_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megatronchannel',
            name='megatron_integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megatron.MegatronIntegration'),
        ),
        migrations.AlterField(
            model_name='megatronchannel',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megatron.CustomerWorkspace'),
        ),
    ]
