# Generated by Django 2.2.9 on 2020-02-24 10:38

from django.db import migrations, models
import django.db.models.deletion


def delete_user_agents(apps, schema_editor):
    PlatformUser = apps.get_model("megatron", "PlatformUser")
    users_repeated = PlatformUser.objects.raw(
        "SELECT * FROM megatron_platformuser WHERE platform_id IN (SELECT platform_id FROM megatron_platformuser GROUP BY platform_id HAVING COUNT(platform_id) > 1)"
    )
    for u in users_repeated:
        u.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("megatron", "0011_auto_20200121_1455"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAgent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_id", models.CharField(db_index=True, max_length=10)),
                ("profile_image", models.CharField(default="", max_length=250)),
                ("username", models.CharField(default="", max_length=250)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("real_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="megatron.MegatronIntegration",
                    ),
                ),
            ],
            options={"unique_together": {("platform_id", "integration")},},
        ),
        migrations.RunPython(delete_user_agents),
    ]
