# Generated by Django 2.2.10 on 2020-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megatron', '0012_platformagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformagent',
            name='platform_id',
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='platform_id',
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
